-----------------------------------------------------------------------------
---------------------------- HOTELES DW DDL ---------------------------------
-----------------------------------------------------------------------------

-- SEQUENCES
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CLIENTES'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE SEQUENCE SEQ_CLIENTES START WITH 1 INCREMENT BY 1;
/ 

BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_HABITACIONES'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE SEQUENCE SEQ_HABITACIONES START WITH 1 INCREMENT BY 1;

BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_EMPLEADOS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE SEQUENCE SEQ_EMPLEADOS START WITH 1 INCREMENT BY 1;

BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_SERVICIOS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE SEQUENCE SEQ_SERVICIOS START WITH 1 INCREMENT BY 1;

BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PAGOS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE SEQUENCE SEQ_PAGOS START WITH 1 INCREMENT BY 1;

BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_RESERVACIONES'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE SEQUENCE SEQ_RESERVACIONES START WITH 1 INCREMENT BY 1;

-- DIM_CLIENTES
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE DIM_CLIENTES CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE DIM_CLIENTES (
    IDCliente NUMBER PRIMARY KEY,
    NombreCompleto VARCHAR2(255),
    Email VARCHAR2(255),
    Numero VARCHAR2(50),
    DNI VARCHAR2(50),
    Edad NUMBER,
    Sexo CHAR(1),
    GrupoEtario VARCHAR2(50)
);

-- DIM_HABITACIONES
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE DIM_HABITACIONES CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE DIM_HABITACIONES (
    IDHabitacion NUMBER PRIMARY KEY,
    NumeroHab NUMBER,
    TipoHab VARCHAR2(50),
    PrecioHab NUMBER(10,2),
    Capacidad NUMBER,
    Estado VARCHAR2(50),
    Categoria VARCHAR2(50)
);

-- DIM_EMPLEADOS
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE DIM_EMPLEADOS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE DIM_EMPLEADOS (
    IDEmpleado NUMBER PRIMARY KEY,
    NombreCompleto VARCHAR2(255),
    Cargo VARCHAR2(100),
    Sexo CHAR(1),
    Edad NUMBER,
    Turno VARCHAR2(50),
    Salario NUMBER(10,2),
    Bonos NUMBER(10,2),
    FechaIngreso DATE,
    AntiguedadAnios NUMBER
);

-- DIM_SERVICIOS
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE DIM_SERVICIOS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE DIM_SERVICIOS (
    IDServicio NUMBER PRIMARY KEY,
    NombreServ VARCHAR2(255),
    PrecioServ NUMBER(10,2),
    HoraReserva VARCHAR2(10)
);

-- DIM_PAGOS
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE DIM_PAGOS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE DIM_PAGOS (
    IDPago NUMBER PRIMARY KEY,
    MetodoPago VARCHAR2(50),
    FechaPago DATE,
    Monto NUMBER(10,2)
);

-- DW_HOTELES_RESERVACIONES (hechos)
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE DW_HOTELES_RESERVACIONES CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE DW_HOTELES_RESERVACIONES (
    IDReservacion NUMBER PRIMARY KEY,
    FechaInicio DATE,
    FechaFin DATE,
    MontoTotal NUMBER(10,2),
    EstadoReservacion VARCHAR2(50),

    IDCliente NUMBER,
    IDHabitacion NUMBER,
    IDServicio NUMBER,

    FOREIGN KEY (IDCliente) REFERENCES DIM_CLIENTES(IDCliente),
    FOREIGN KEY (IDHabitacion) REFERENCES DIM_HABITACIONES(IDHabitacion),
    FOREIGN KEY (IDServicio) REFERENCES DIM_SERVICIOS(IDServicio),
);

-----------------------------------------------------------------------------
-----------ELIMINACIÓN DE LAS SEQUENCES Y CREACION DE LAS MISMAS-------------
-----------------------------------------------------------------------------

-- CLIENTES
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CLIENTES'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE SEQUENCE SEQ_CLIENTES START WITH 1 INCREMENT BY 1;
/

-- EMPLEADOS
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_EMPLEADOS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE SEQUENCE SEQ_EMPLEADOS START WITH 1 INCREMENT BY 1;
/

-- HABITACIONES
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_HABITACIONES'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE SEQUENCE SEQ_HABITACIONES START WITH 1 INCREMENT BY 1;
/

-- SERVICIOS
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_SERVICIOS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE SEQUENCE SEQ_SERVICIOS START WITH 1 INCREMENT BY 1;
/

-- PAGOS
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PAGOS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE SEQUENCE SEQ_PAGOS START WITH 1 INCREMENT BY 1;
/

-- RESERVACIONES
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_RESERVACIONES'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE SEQUENCE SEQ_RESERVACIONES START WITH 1 INCREMENT BY 1;
/

-----------------------------------------------------------------------------
----------------------BORRAR LA DATA DE LAS TABLAS---------------------------
-----------------------------------------------------------------------------

BEGIN
    --ESTA DEBE DE IR PRIMERO POR LAS RELACIONES QUE EXISTEN DENTRO
    EXECUTE IMMEDIATE 'TRUNCATE TABLE DW_HOTELES_RESERVACIONES';
    
    EXECUTE IMMEDIATE 'TRUNCATE TABLE DIM_CLIENTES';

    EXECUTE IMMEDIATE 'TRUNCATE TABLE DIM_EMPLEADOS';

    EXECUTE IMMEDIATE 'TRUNCATE TABLE DIM_HABITACIONES';

    EXECUTE IMMEDIATE 'TRUNCATE TABLE DIM_PAGOS';

    EXECUTE IMMEDIATE 'TRUNCATE TABLE DIM_SERVICIOS';
    
END;