--TOP 5 MESES DE MAYOR RESERVACIÓN
CREATE OR REPLACE VIEW VISTA_TOP5_MESES_RESERVAS AS
SELECT *
FROM (
    SELECT 
        TO_CHAR(FechaInicio, 'YYYY-MM') AS Mes,
        COUNT(*) AS TotalReservas
    FROM DW_HOTELES_RESERVACIONES
    GROUP BY TO_CHAR(FechaInicio, 'YYYY-MM')
    ORDER BY TotalReservas DESC
)
WHERE ROWNUM <= 5;

--TOP 5 SERVICIOS MAS SOLICITADOS
CREATE OR REPLACE VIEW VISTA_TOP5_SERVICIOS AS
SELECT *
FROM (
    SELECT
        s.NombreServ,
        COUNT(*) AS TotalUso
    FROM DW_HOTELES_RESERVACIONES rs
    JOIN DIM_SERVICIOS s ON rs.IDServicio = s.IDServicio
    GROUP BY s.NombreServ
    ORDER BY TotalUso DESC
)
WHERE ROWNUM <= 5;

--METRICAS PARA VER CANTIDAD DE RESERVACIONES CANCELADAS, CONFIRMADAS Y FINALIZADAS
CREATE OR REPLACE VIEW VISTA_ESTADO_RESERVAS AS
SELECT estadoreservacion, COUNT(*) AS Total
FROM DW_HOTELES_RESERVACIONES
GROUP BY estadoreservacion;

--INGRESO MENSUAL
CREATE OR REPLACE VIEW VISTA_INGRESOS_MENSUALES AS
SELECT
    TO_CHAR(FechaInicio, 'YYYY-MM') AS Mes,
    SUM(montototal) AS TotalIngresos
FROM DW_HOTELES_RESERVACIONES
GROUP BY TO_CHAR(FechaInicio, 'YYYY-MM')
ORDER BY Mes;

--REPORTE DE CLIENTES (CUANTAS RESERVAS TIENE CUALES HABITACIONES PREFIERE)
CREATE OR REPLACE VIEW VISTA_RESERVAS_POR_CLIENTE_HABITACION AS
SELECT
    c.NombreCompleto,
    h.Categoria,
    COUNT(*) AS TotalReservas,
    ROUND(AVG(r.montototal), 2) AS PromedioReserva
FROM DW_HOTELES_RESERVACIONES r
JOIN DIM_CLIENTES c ON r.IDCliente = c.IDCliente
JOIN DIM_HABITACIONES h ON r.IDHabitacion = h.IDHabitacion
GROUP BY c.NombreCompleto, h.Categoria
ORDER BY c.NombreCompleto, TotalReservas DESC;
